name: PullRequest
on:
  pull_request:
    branches:
      - master

jobs:
  test-and-build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Lint
        run: yarn lint
      - name: Test Mobile
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          headless: true
      - name: Test Desktop
        uses: cypress-io/github-action@v1
        with:
          command: cypress run --config viewportWidth=1280,viewportHeight=80
          browser: chrome
          headless: true
      - name: Build
        run: ./.github/workflows/build-frontend.sh

  build-firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: ./.github/workflows/build-firebase.sh
